spring:
  main:
    banner-mode: false
  datasource:
    url: jdbc:h2:mem:charity;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration
cantor:
  baseUrl: https://api.freecurrencyapi.com/v1/latest
  securityKey: ${CANTOR_KEY}